import type { Metadata } from "next";
import "@/style/global.css";
import { Providers } from "@/provider/QueryClientProvider";
import { ThemeProvider } from "../provider/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default Layout;
